spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  config:
    import:
      - classpath:/application-prod.yml


logging:
  level:
    org:
      hibernate:
        type:
          description:
            sql: trace