spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: test
    password:

  config:
    import:
      - classpath:/application-prod.yml


logging:
  level:
    org:
      hibernate:
        type:
          description:
            sql: trace